Fixed bug after upgrade to Python 3.5
Hit this issue while transforming GoogLeNetv1 to PNG:
RuntimeError: OrderedDict mutated during iteration

Fixed by making a copy of the keys (in a list) and iterating
across the list, instead of iterating across the dictionary.